require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - 'app/views/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/Documentation:
  Include:
    - app/models/**/*
    - lib/**/*

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Rails/HasAndBelongsToMany:
  Enabled: false
