require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6.6
  Exclude:
    - 'app/views/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Style/Documentation:
  Include:
    - app/models/**/*
    - lib/**/*

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes
