# config/app.yml for rails-settings-cached
defaults: &defaults
  application.name: TeamPlan
  club.name: Defrog
  club.hostname: teamplan.defrog.nl
  club.address:
  club.zip:
  club.city: Arnhem
  club.email: helpdesk@defrog.nl
  club.phone:
  club.contact_name: Thimo Jansen
  club.helpdesk_email: helpdesk@defrog.nl
  clubdata.urls.competities: https://data.sportlink.com/teams?competitieperiode=ALLES&teamsoort=bond&geslacht=alles&spelsoort=alles&competitiesoort=alles&leeftijdscategorie=alles&gebruiklokaleteamgegevens=NEE
  clubdata.client_id: 123456

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
