# config/app.yml for rails-settings-cached
defaults: &defaults
  application.name: TeamPlan
  club.name: Defrog
  club.name_short: Defrog
  club.hostname: teamplan.defrog.nl
  club.sportscenter:
  club.address:
  club.zip:
  club.city: Arnhem
  club.email: helpdesk@defrog.nl
  club.phone:
  club.contact_name: Thimo Jansen
  club.helpdesk_email: helpdesk@defrog.nl
  clubdata.urls.competities: https://data.sportlink.com/teams?teamsoort=bond&spelsoort=ve&gebruiklokaleteamgegevens=NEE
  clubdata.urls.poulestand: https://data.sportlink.com/poulestand?gebruiklokaleteamgegevens=NEE
  clubdata.urls.poule-programma: https://data.sportlink.com/poule-programma?eigenwedstrijden=NEE&gebruiklokaleteamgegevens=NEE
  clubdata.urls.pouleuitslagen: https://data.sportlink.com/pouleuitslagen?eigenwedstrijden=NEE&gebruiklokaleteamgegevens=NEE
  clubdata.urls.uitslagen: https://data.sportlink.com/uitslagen?gebruiklokaleteamgegevens=NEE&eigenwedstrijden=JA&thuis=JA&uit=JA
  clubdata.urls.team-indeling: https://data.sportlink.com/team-indeling?lokaleteamcode=-1&teampersoonrol=ALLES&toonlidfoto=JA
  clubdata.client_id:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
