# config/app.yml for rails-settings-cached
defaults: &defaults
  application.name: TeamPlan
  application.hostname: teamplan.defrog.nl
  application.email: helpdesk@defrog.nl
  application.contact_name: Thimo Jansen
  application.maintenance: false
  application.favicon_url: /favicon.ico
  club.name: Defrog
  club.name_short: Defrog
  club.website: https://teamplan.defrog.nl/
  club.sportscenter:
  club.address:
  club.zip:
  club.city: Arnhem
  club.phone:
  club.relatiecode:
  club.logo_url:
  club.member_administration.email:
  clubdata.urls.competities: https://data.sportlink.com/teams?teamsoort=bond&spelsoort=ve&gebruiklokaleteamgegevens=NEE
  clubdata.urls.poulestand: https://data.sportlink.com/poulestand?gebruiklokaleteamgegevens=NEE
  clubdata.urls.poule-programma: https://data.sportlink.com/poule-programma?eigenwedstrijden=NEE&gebruiklokaleteamgegevens=NEE&aantaldagen=365&weekoffset=-2
  clubdata.urls.pouleuitslagen: https://data.sportlink.com/pouleuitslagen?eigenwedstrijden=NEE&gebruiklokaleteamgegevens=NEE&aantaldagen=30&weekoffset=-4&
  clubdata.urls.uitslagen: https://data.sportlink.com/uitslagen?aantalregels=300&gebruiklokaleteamgegevens=NEE&sorteervolgorde=datum-omgekeerd&thuis=JA&uit=JA
  clubdata.urls.team-indeling: https://data.sportlink.com/team-indeling?lokaleteamcode=-1&teampersoonrol=ALLES&toonlidfoto=JA
  clubdata.urls.wedstrijd-accommodatie: https://data.sportlink.com/wedstrijd-accommodatie
  clubdata.urls.afgelastingen: https://data.sportlink.com/afgelastingen?aantalregels=100&weekoffset=-1
  clubdata.urls.club_logos: http://bin617.website-voetbal.nl/sites/voetbal.nl/files/knvblogos/
  clubdata.client_id:
  fontawesome.version: v5.5.0
  fontawesome.integrity:
  google.maps.base_url: https://www.google.com/maps/embed/v1/
  google.maps.api-key:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
