default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: teamplan_defrog_nl

test:
  <<: *default
  database: team_plan_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
