# Teams and competitions - every day at 20:00
clubdata_teams_and_competitions:
  cron: "0 20 * * *"
  class: ClubdataScheduler::TeamsAndCompetitionsJob

# Own results, every 15 minutes on saturday - otherwise every hour
clubdata_results:
  cron: "5 * * * *"
  class: ClubdataScheduler::ResultsJob

clubdata_results_saturday:
  cron: "*/15 * * * 6"
  class: ClubdataScheduler::ResultsJob

# Cancelations, every hour
clubdata_cancelations:
  cron: "15 * * * *"
  class: ClubdataScheduler::CancelationsJob

# Competitions, matches, standing, results - every hour on saturday, otherwise at 23:05,
clubdata_poules:
  cron: "5 23 * * *"
  class: ClubdataScheduler::PoulesJob

clubdata_poules_saturday:
  cron: "10 * * * 6"
  class: ClubdataScheduler::PoulesJob

# Team member photos - every sunday at 22:15
clubdata_team_photos:
  cron: "15 22 * * 7"
  class: ClubdataScheduler::TeamPhotosJob

# Database cleanup - every sunday at 0:10
database_cleanup:
  cron: "0 10 * * 7"
  class: DatabaseCleanupJob

# Referees from the website, every hour
website_referees:
  cron: "30 * * * *"
  class: ScheduleRefereeImportJob
