name: Delete old workflow runs
on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: "30"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: ${{ github.event.inputs.days }}
