name: Auto-merge Dependabot PR's

on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  test:
    name: Auto-merge minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: koj-co/dependabot-pr-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-label: true
          merge-minor: true
          merge-patch: true
          merge-commit: Merge #$PR_NUMBER ($PR_TITLE)
